// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import ReduxProvider from "./ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased duration-300`}>
        <ReduxProvider>
          <Navbar />
          <main>{children}</main>
          {/* Footer would go here */}
        </ReduxProvider>
      </body>
    </html>
  );
}
