import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import { ClerkProvider } from "@clerk/nextjs";
import { ApolloProviderWrapper } from "@/lib/apollo-provider";
import { ReactQueryProvider } from "@/lib/react-query-provider";
import { WebSocketProvider } from "@/providers/WebSocketProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased duration-300`}>
        <ClerkProvider touchSession={false}>
          <ApolloProviderWrapper>
            <ReactQueryProvider>
              <WebSocketProvider>
                <ClientLayout>{children}</ClientLayout>
              </WebSocketProvider>
            </ReactQueryProvider>
          </ApolloProviderWrapper>
        </ClerkProvider>
      </body>
    </html>
  );
}
